name: "automatic-pre-release-by-tags"

on:
  push:
    tags:
      - "Version-*"

jobs:
  release:
    name: "Create Release"
    runs-on: "ubuntu-latest"

    steps:
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: true
          files: |
            Vendor-Frameworks/*.xcframework.zip
